name: First WorkFlow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
          echo "Hello World"
          echo "Multiline Working!"
      - name: Print Goodbye
        run: echo "Done -Bye";
